### ISSUE TITLE
Stalling startup when using /16 IP range

### ISSUE THREAD

**Issue by jshep321** [jjmonteiro/ha-net-monitor#2]
Hi,
Looks like a great start.  One item that will need to be solved is that it blocks other items at startup while scanning.  

I assume it is blocking until the first scan is complete?  My network is a 10.0.0.0/16 setup and therefore has 65k addresses to scan.  I did put this at the end of my configuration.yaml file but that has no impact I suppose.  It hung everything up so my zigbee network didn't function for many minutes after a restart (CPU at normal load).

**Comment by jjmonteiro** [comment]
wow that's a massive address pool I never quite anticipated but I can foresee some trouble!
I'll try to find a fix for it, meanwhile limit your ip range to /24
